-- UnrealTournament3 SoundPack
PVPSound_UnrealTournament3Durations = { }

PVPSound_UnrealTournament3Durations[1]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\CountDown\\FiveKillsRemain.mp3",												duration = 1.750 }
PVPSound_UnrealTournament3Durations[2]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\CountDown\\OneKillRemains.mp3",												duration = 2.011 }
PVPSound_UnrealTournament3Durations[3]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\CountDown\\TenKillsRemain.mp3",												duration = 1.750 }
PVPSound_UnrealTournament3Durations[4]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\GameStatus\\AllianceDominating.mp3",											duration = 1.828 }
PVPSound_UnrealTournament3Durations[5]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\GameStatus\\AllianceWins.mp3",												duration = 1.993 }
PVPSound_UnrealTournament3Durations[6]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\GameStatus\\EndOfRound.mp3",													duration = 1.071 }
PVPSound_UnrealTournament3Durations[7]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\GameStatus\\FinalRound.mp3",													duration = 1.201 }
PVPSound_UnrealTournament3Durations[8]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\GameStatus\\HordeDominating.mp3",											duration = 1.724 }
PVPSound_UnrealTournament3Durations[9]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\GameStatus\\HordeWins.mp3",													duration = 1.906 }
PVPSound_UnrealTournament3Durations[10]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\GameStatus\\PlayYouAreOnBlue.mp3",											duration = 2.220 }
PVPSound_UnrealTournament3Durations[11]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\GameStatus\\PlayYouAreOnRed.mp3",											duration = 2.298 }
PVPSound_UnrealTournament3Durations[12]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\GameStatus\\PrepareForBattle.mp3",											duration = 1.776 }
PVPSound_UnrealTournament3Durations[13]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\Dominating.mp3",														duration = 1.593 }
PVPSound_UnrealTournament3Durations[14]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\DoubleKill.mp3",														duration = 1.645 }
PVPSound_UnrealTournament3Durations[15]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\FirstBlood.mp3",														duration = 2.429 }
PVPSound_UnrealTournament3Durations[16]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\Godlike.mp3",															duration = 1.541 }
PVPSound_UnrealTournament3Durations[17]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\KillingSpree.mp3",													duration = 2.533 }
PVPSound_UnrealTournament3Durations[18]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\Massacre.mp3",														duration = 2.481 }
PVPSound_UnrealTournament3Durations[19]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\MegaKill.mp3",														duration = 2.612 }
PVPSound_UnrealTournament3Durations[20]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\MonsterKill.mp3",														duration = 2.899 }
PVPSound_UnrealTournament3Durations[21]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\MultiKill.mp3",														duration = 1.933 }
PVPSound_UnrealTournament3Durations[22]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\Payback.mp3",															duration = 2.168 }
PVPSound_UnrealTournament3Durations[23]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\Rampage.mp3",															duration = 2.507 }
PVPSound_UnrealTournament3Durations[24]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\Retribution.mp3",														duration = 2.847 }
PVPSound_UnrealTournament3Durations[25]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\UltraKill.mp3",														duration = 1.567 }
PVPSound_UnrealTournament3Durations[26]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Spree\\Unstoppable.mp3",														duration = 2.638 }
PVPSound_UnrealTournament3Durations[27]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Test\\Pancake.mp3",															duration = 2.089 }
PVPSound_UnrealTournament3Durations[28]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\ALLIANCE_Node_Defense.mp3",								duration = 1.724 }
PVPSound_UnrealTournament3Durations[29]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\ALLIANCE_Node_Offense.mp3",								duration = 1.985 }
PVPSound_UnrealTournament3Durations[30]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\ALLIANCE_TowerNode_Defense.mp3",							duration = 2.037 }
PVPSound_UnrealTournament3Durations[31]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\ALLIANCE_TowerNode_Destroyed.mp3",						duration = 2.115 }
PVPSound_UnrealTournament3Durations[32]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\ALLIANCE_TowerNode_Offense.mp3",							duration = 2.507 }
PVPSound_UnrealTournament3Durations[33]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\HORDE_Node_Defense.mp3",									duration = 1.828 }
PVPSound_UnrealTournament3Durations[34]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\HORDE_Node_Offense.mp3",									duration = 2.011 }
PVPSound_UnrealTournament3Durations[35]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\HORDE_TowerNode_Defense.mp3",							duration = 2.220 }
PVPSound_UnrealTournament3Durations[36]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\HORDE_TowerNode_Destroyed.mp3",							duration = 2.063 }
PVPSound_UnrealTournament3Durations[37]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_AlteracValley\\HORDE_TowerNode_Offense.mp3",							duration = 2.481 }
PVPSound_UnrealTournament3Durations[38]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_ArathiBasin\\ALLIANCE_Base_Defense.mp3",								duration = 1.776 }
PVPSound_UnrealTournament3Durations[39]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_ArathiBasin\\ALLIANCE_Base_Offense.mp3",								duration = 2.272 }
PVPSound_UnrealTournament3Durations[40]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_ArathiBasin\\HORDE_Base_Defense.mp3",									duration = 2.037 }
PVPSound_UnrealTournament3Durations[41]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_ArathiBasin\\HORDE_Base_Offense.mp3",									duration = 2.168 }
PVPSound_UnrealTournament3Durations[42]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_EyeoftheStorm\\ALLIANCE_Base_Defense.mp3",								duration = 1.776 }
PVPSound_UnrealTournament3Durations[43]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_EyeoftheStorm\\ALLIANCE_Base_Offense.mp3",								duration = 2.272 }
PVPSound_UnrealTournament3Durations[44]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_EyeoftheStorm\\ALLIANCE_Scores.mp3",									duration = 1.593 }
PVPSound_UnrealTournament3Durations[45]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_EyeoftheStorm\\HORDE_Base_Defense.mp3",									duration = 2.037 }
PVPSound_UnrealTournament3Durations[46]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_EyeoftheStorm\\HORDE_Base_Offense.mp3",									duration = 2.168 }
PVPSound_UnrealTournament3Durations[47]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_EyeoftheStorm\\HORDE_Scores.mp3",										duration = 1.541 }
PVPSound_UnrealTournament3Durations[48]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_IsleofConquest\\ALLIANCE_Base_Defense.mp3",								duration = 1.776 }
PVPSound_UnrealTournament3Durations[49]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_IsleofConquest\\ALLIANCE_Base_Offense.mp3",								duration = 2.272 }
PVPSound_UnrealTournament3Durations[50]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_IsleofConquest\\BarricadeDestroyed.mp3",								duration = 1.776 }
PVPSound_UnrealTournament3Durations[51]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_IsleofConquest\\BarricadeDestroyedBlueCoreIsVulnerable.mp3",			duration = 3.631 }
PVPSound_UnrealTournament3Durations[52]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_IsleofConquest\\BarricadeDestroyedRedCoreIsVulnerable.mp3",				duration = 3.657 }
PVPSound_UnrealTournament3Durations[53]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_IsleofConquest\\HORDE_Base_Defense.mp3",								duration = 2.037 }
PVPSound_UnrealTournament3Durations[54]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_IsleofConquest\\HORDE_Base_Offense.mp3",								duration = 2.168 }
PVPSound_UnrealTournament3Durations[55]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_StrandoftheAncients\\ALLIANCE_Node_Defense.mp3",						duration = 1.724 }
PVPSound_UnrealTournament3Durations[56]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_StrandoftheAncients\\AttackTheEnemyCore.mp3",							duration = 1.645 }
PVPSound_UnrealTournament3Durations[57]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_StrandoftheAncients\\BarricadeDestroyed.mp3",							duration = 1.776 }
PVPSound_UnrealTournament3Durations[58]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_StrandoftheAncients\\BarricadeDestroyedBlueCoreIsVulnerable.mp3",		duration = 3.631 }
PVPSound_UnrealTournament3Durations[59]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_StrandoftheAncients\\BarricadeDestroyedRedCoreIsVulnerable.mp3",		duration = 3.657 }
PVPSound_UnrealTournament3Durations[60]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_StrandoftheAncients\\DefendYourCore.mp3",								duration = 1.462 }
PVPSound_UnrealTournament3Durations[61]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_StrandoftheAncients\\HORDE_Node_Defense.mp3",							duration = 1.828 }
PVPSound_UnrealTournament3Durations[62]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TheBattleforGilneas\\ALLIANCE_Base_Defense.mp3",						duration = 1.776 }
PVPSound_UnrealTournament3Durations[63]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TheBattleforGilneas\\ALLIANCE_Base_Offense.mp3",						duration = 2.272 }
PVPSound_UnrealTournament3Durations[64]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TheBattleforGilneas\\HORDE_Base_Defense.mp3",							duration = 2.037 }
PVPSound_UnrealTournament3Durations[65]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TheBattleforGilneas\\HORDE_Base_Offense.mp3",							duration = 2.168 }
PVPSound_UnrealTournament3Durations[66]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\ALLIANCE_Base_Defense.mp3",									duration = 1.776 }
PVPSound_UnrealTournament3Durations[67]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\ALLIANCE_Base_Offense.mp3",									duration = 2.272 }
PVPSound_UnrealTournament3Durations[68]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\ALLIANCE_TowerNode_Destroyed.mp3",							duration = 2.063 }
PVPSound_UnrealTournament3Durations[69]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\ALLIANCE_TowerNode_HeavilyDamaged.mp3",						duration = 2.664 }
PVPSound_UnrealTournament3Durations[70]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\HORDE_Base_Defense.mp3",										duration = 2.037 }
PVPSound_UnrealTournament3Durations[71]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\HORDE_Base_Offense.mp3",										duration = 2.168 }
PVPSound_UnrealTournament3Durations[72]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\HORDE_TowerNode_Destroyed.mp3",								duration = 2.115 }
PVPSound_UnrealTournament3Durations[73]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\HORDE_TowerNode_HeavilyDamaged.mp3",							duration = 2.612 }
PVPSound_UnrealTournament3Durations[74]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\PlayYouAreOnBlueAttackTheEnemyCore.mp3",						duration = 3.944 }
PVPSound_UnrealTournament3Durations[75]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\PlayYouAreOnBlueDefendYourCore.mp3",							duration = 3.761 }
PVPSound_UnrealTournament3Durations[76]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\PlayYouAreOnRedAttackTheEnemyCore.mp3",						duration = 4.022 }
PVPSound_UnrealTournament3Durations[77]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TolBarad\\PlayYouAreOnRedDefendYourCore.mp3",							duration = 3.840 }
PVPSound_UnrealTournament3Durations[78]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\ALLIANCE_Flag_Dropped.mp3",									duration = 1.750 }
PVPSound_UnrealTournament3Durations[79]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\ALLIANCE_Flag_Returned.mp3",									duration = 1.515 }
PVPSound_UnrealTournament3Durations[80]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\ALLIANCE_Flag_Taken.mp3",									duration = 1.436 }
PVPSound_UnrealTournament3Durations[81]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\ALLIANCE_Inc_Lead.mp3",										duration = 2.142 }
PVPSound_UnrealTournament3Durations[82]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\ALLIANCE_Scores.mp3",										duration = 1.593 }
PVPSound_UnrealTournament3Durations[83]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\ALLIANCE_Takes_Lead.mp3",									duration = 1.828 }
PVPSound_UnrealTournament3Durations[84]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\HORDE_Flag_Dropped",											duration = 1.541 }
PVPSound_UnrealTournament3Durations[85]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\HORDE_Flag_Returned.mp3",									duration = 1.697 }
PVPSound_UnrealTournament3Durations[86]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\HORDE_Flag_Taken.mp3",										duration = 1.645 }
PVPSound_UnrealTournament3Durations[87]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\HORDE_Inc_Lead.mp3",											duration = 2.115 }
PVPSound_UnrealTournament3Durations[88]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\HORDE_Scores.mp3",											duration = 1.541 }
PVPSound_UnrealTournament3Durations[89]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\HORDE_Takes_Lead.mp3",										duration = 1.671 }
PVPSound_UnrealTournament3Durations[90]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_TwinPeaks\\Overtime.mp3",												duration = 1.097 }
PVPSound_UnrealTournament3Durations[91]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\ALLIANCE_Flag_Dropped.mp3",								duration = 1.750 }
PVPSound_UnrealTournament3Durations[92]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\ALLIANCE_Flag_Returned.mp3",								duration = 1.515 }
PVPSound_UnrealTournament3Durations[93]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\ALLIANCE_Flag_Taken.mp3",									duration = 1.436 }
PVPSound_UnrealTournament3Durations[94]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\ALLIANCE_Inc_Lead.mp3",									duration = 2.142 }
PVPSound_UnrealTournament3Durations[95]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\ALLIANCE_Scores.mp3",										duration = 1.593 }
PVPSound_UnrealTournament3Durations[96]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\ALLIANCE_Takes_Lead.mp3",									duration = 1.828 }
PVPSound_UnrealTournament3Durations[97]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\HORDE_Flag_Dropped",										duration = 1.541 }
PVPSound_UnrealTournament3Durations[98]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\HORDE_Flag_Returned.mp3",									duration = 1.697 }
PVPSound_UnrealTournament3Durations[99]		= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\HORDE_Flag_Taken.mp3",									duration = 1.645 }
PVPSound_UnrealTournament3Durations[100]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\HORDE_Inc_Lead.mp3",										duration = 2.115 }
PVPSound_UnrealTournament3Durations[101]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\HORDE_Scores.mp3",										duration = 1.541 }
PVPSound_UnrealTournament3Durations[102]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\HORDE_Takes_Lead.mp3",									duration = 1.671 }
PVPSound_UnrealTournament3Durations[103]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_WarsongGulch\\Overtime.mp3",											duration = 1.097 }
PVPSound_UnrealTournament3Durations[104]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\ALLIANCE_Base_Defense.mp3",								duration = 1.776 }
PVPSound_UnrealTournament3Durations[105]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\ALLIANCE_Base_Offense.mp3",								duration = 2.272 }
PVPSound_UnrealTournament3Durations[106]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\ALLIANCE_TowerNode_Destroyed.mp3",							duration = 2.063 }
PVPSound_UnrealTournament3Durations[107]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\ALLIANCE_TowerNode_HeavilyDamaged.mp3",					duration = 2.664 }
PVPSound_UnrealTournament3Durations[108]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\HORDE_Base_Defense.mp3",									duration = 2.037 }
PVPSound_UnrealTournament3Durations[109]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\HORDE_Base_Offense.mp3",									duration = 2.168 }
PVPSound_UnrealTournament3Durations[110]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\HORDE_TowerNode_Destroyed.mp3",							duration = 2.115 }
PVPSound_UnrealTournament3Durations[111]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\HORDE_TowerNode_HeavilyDamaged.mp3",						duration = 2.612 }
PVPSound_UnrealTournament3Durations[112]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\PlayYouAreOnBlueAttackTheEnemyCore.mp3",					duration = 3.944 }
PVPSound_UnrealTournament3Durations[113]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\PlayYouAreOnBlueDefendYourCore.mp3",						duration = 3.761 }
PVPSound_UnrealTournament3Durations[114]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\PlayYouAreOnRedAttackTheEnemyCore.mp3",					duration = 4.022 }
PVPSound_UnrealTournament3Durations[115]	= { dir = "Interface\\AddOns\\PVPSound\\Sounds\\UnrealTournament3\\Zone_Wintergrasp\\PlayYouAreOnRedDefendYourCore.mp3",						duration = 3.840 }